// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mutex

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MutexServiceClient is the client API for MutexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MutexServiceClient interface {
	Enter(ctx context.Context, in *RequestCriticalSection, opts ...grpc.CallOption) (*Response, error)
	Exit(ctx context.Context, in *Response, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type mutexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMutexServiceClient(cc grpc.ClientConnInterface) MutexServiceClient {
	return &mutexServiceClient{cc}
}

func (c *mutexServiceClient) Enter(ctx context.Context, in *RequestCriticalSection, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/mutex.mutexService/Enter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mutexServiceClient) Exit(ctx context.Context, in *Response, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/mutex.mutexService/Exit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MutexServiceServer is the server API for MutexService service.
// All implementations must embed UnimplementedMutexServiceServer
// for forward compatibility
type MutexServiceServer interface {
	Enter(context.Context, *RequestCriticalSection) (*Response, error)
	Exit(context.Context, *Response) (*EmptyResponse, error)
	mustEmbedUnimplementedMutexServiceServer()
}

// UnimplementedMutexServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMutexServiceServer struct {
}

func (UnimplementedMutexServiceServer) Enter(context.Context, *RequestCriticalSection) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enter not implemented")
}
func (UnimplementedMutexServiceServer) Exit(context.Context, *Response) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exit not implemented")
}
func (UnimplementedMutexServiceServer) mustEmbedUnimplementedMutexServiceServer() {}

// UnsafeMutexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MutexServiceServer will
// result in compilation errors.
type UnsafeMutexServiceServer interface {
	mustEmbedUnimplementedMutexServiceServer()
}

func RegisterMutexServiceServer(s grpc.ServiceRegistrar, srv MutexServiceServer) {
	s.RegisterService(&MutexService_ServiceDesc, srv)
}

func _MutexService_Enter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCriticalSection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutexServiceServer).Enter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mutex.mutexService/Enter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutexServiceServer).Enter(ctx, req.(*RequestCriticalSection))
	}
	return interceptor(ctx, in, info, handler)
}

func _MutexService_Exit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Response)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutexServiceServer).Exit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mutex.mutexService/Exit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutexServiceServer).Exit(ctx, req.(*Response))
	}
	return interceptor(ctx, in, info, handler)
}

// MutexService_ServiceDesc is the grpc.ServiceDesc for MutexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MutexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mutex.mutexService",
	HandlerType: (*MutexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enter",
			Handler:    _MutexService_Enter_Handler,
		},
		{
			MethodName: "Exit",
			Handler:    _MutexService_Exit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mutex/mutex.proto",
}
