// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mutex

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MutexServiceClient is the client API for MutexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MutexServiceClient interface {
	Enter(ctx context.Context, in *RequestCriticalSection, opts ...grpc.CallOption) (MutexService_EnterClient, error)
	Exit(ctx context.Context, in *EmptyResponse, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type mutexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMutexServiceClient(cc grpc.ClientConnInterface) MutexServiceClient {
	return &mutexServiceClient{cc}
}

func (c *mutexServiceClient) Enter(ctx context.Context, in *RequestCriticalSection, opts ...grpc.CallOption) (MutexService_EnterClient, error) {
	stream, err := c.cc.NewStream(ctx, &MutexService_ServiceDesc.Streams[0], "/mutex.mutexService/enter", opts...)
	if err != nil {
		return nil, err
	}
	x := &mutexServiceEnterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MutexService_EnterClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type mutexServiceEnterClient struct {
	grpc.ClientStream
}

func (x *mutexServiceEnterClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mutexServiceClient) Exit(ctx context.Context, in *EmptyResponse, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/mutex.mutexService/exit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MutexServiceServer is the server API for MutexService service.
// All implementations must embed UnimplementedMutexServiceServer
// for forward compatibility
type MutexServiceServer interface {
	Enter(*RequestCriticalSection, MutexService_EnterServer) error
	Exit(context.Context, *EmptyResponse) (*EmptyResponse, error)
	mustEmbedUnimplementedMutexServiceServer()
}

// UnimplementedMutexServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMutexServiceServer struct {
}

func (UnimplementedMutexServiceServer) Enter(*RequestCriticalSection, MutexService_EnterServer) error {
	return status.Errorf(codes.Unimplemented, "method Enter not implemented")
}
func (UnimplementedMutexServiceServer) Exit(context.Context, *EmptyResponse) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exit not implemented")
}
func (UnimplementedMutexServiceServer) mustEmbedUnimplementedMutexServiceServer() {}

// UnsafeMutexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MutexServiceServer will
// result in compilation errors.
type UnsafeMutexServiceServer interface {
	mustEmbedUnimplementedMutexServiceServer()
}

func RegisterMutexServiceServer(s grpc.ServiceRegistrar, srv MutexServiceServer) {
	s.RegisterService(&MutexService_ServiceDesc, srv)
}

func _MutexService_Enter_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestCriticalSection)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MutexServiceServer).Enter(m, &mutexServiceEnterServer{stream})
}

type MutexService_EnterServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type mutexServiceEnterServer struct {
	grpc.ServerStream
}

func (x *mutexServiceEnterServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _MutexService_Exit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutexServiceServer).Exit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mutex.mutexService/exit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutexServiceServer).Exit(ctx, req.(*EmptyResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// MutexService_ServiceDesc is the grpc.ServiceDesc for MutexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MutexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mutex.mutexService",
	HandlerType: (*MutexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "exit",
			Handler:    _MutexService_Exit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "enter",
			Handler:       _MutexService_Enter_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mutex/mutex.proto",
}
